### PR TITLE
Data loading

### PR DESCRIPTION
**Pull request by graceyraspberry**
Added data loading tutorials for MiXCR and 10x data, got feedback from Tijaan and implemented modifications.

### CODE REVIEW

**Comment by vadimnazarov** [comment]
Hi Grace,
thank you! You did an amazing job. In both tutorials you explicitly show what are the outputs and what files should serve as inputs, which is very important for beginners. Few suggestions.

Load MiXCR:
- In the "Load into Immunarch" section can you add two sub-sections please: one with "loading a single file" (what you have now), and second with "loading a folder" so you can show what would be the output when you apply repLoad to a folder with several files and a metadata.txt file?

Load 10X:
- Change name to "Loading 10X Genomics Data" to make sure people understand the platform
- Make a note that people should use the "filtered contigs" files because they contain barcode information
- Create a section "Paired-chain data", describe that immunarch can parse both single-chain and paired-chain single-cell data, and link there this tutorial for more information: https://immunarch.com/articles/web_only/v21_singlecell.html

General:
- If you are interested in thinking about efficient communication and how to make easy-to-read docs for the community, check this tutorial: https://immunarch.com/articles/web_only/v21_singlecell.html We have the "exec summary" section there. Do you think adding very short "Exec summary"s to your tutorials would be beneficial? Feel free to experiment and let me know if you have any questions or suggestions.

**Comment by graceyraspberry** [comment]
Hi Vadim, 
I made the modifications you suggested! I read over the single cell tutorial and added a few more links that make it easier to read. I left out the executive summary because it makes sense for larger tutorials, but it seems like too much for small data loading ones. 

One thing that would be helpful would be to have a different doc that details different types of data from MiXCR and 10x, and what kind of experiments and data types these are suitable for. I can help put this together if you think that this would be helpful to users.

**Comment by vadimnazarov** [comment]
Perfect, thank you!

> I left out the executive summary because it makes sense for larger tutorials, but it seems like too much for small data loading ones.

Yes, totally valid point.

> One thing that would be helpful would be to have a different doc that details different types of data from MiXCR and 10x, and what kind of experiments and data types these are suitable for.

A very interesting suggestion as it helps resolve one of the major issues for beginners. What do you have in mind when you suggest creating a different document? Wouldn't it be better to upgrade the current one so people can have all the information in one place?

**Comment by graceyraspberry** [comment]
I can add a couple sentences under each tutorial that summarize when MiXCR and 10x are used. Any other changes that I should make?

**Comment by vadimnazarov** [comment]
> Hmm, a different doc may be too much now that I think about it.

Yes, I am afraid so! People usually would like to have all the important information on specific tpoic in one place.

> I can add a couple sentences under each tutorial that summarize when MiXCR and 10x are used, does that sound good?

Sounds very good! Let's do this. I will review soon after the update, and we can officially publish it and start collecting the feedback.

**Comment by graceyraspberry** [comment]
Updated the descriptions!

**Pull request merged**
